apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30000  # Choose a port number within the range 30000-32767

